# Generated by Django 6.0.1 on 2026-01-22 07:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('tricycle_assigne', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_livraison', 'En Livraison')], default='inactif', max_length=20)),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_point_vente', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type_client', models.CharField(choices=[('revendeur', 'Revendeur'), ('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='revendeur', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qt_commandee', models.PositiveIntegerField(help_text='Quantité commandée')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('validee', 'Validée'), ('en_cours', 'En Cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_assignees', to='logistics.agentcommercial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='logistics.client')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_livree', models.PositiveIntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_preparation', 'En Préparation'), ('en_route', 'En Route'), ('livre', 'Livré'), ('echec', 'Échec')], default='en_preparation', max_length=20)),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='preuves_livraison/%Y/%m/')),
                ('signature_url', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/')),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='logistics.agentcommercial')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='logistics.client')),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='logistics.commande')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
