# Generated by Django 6.0.1 on 2026-01-22 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcommercial',
            name='date_embauche',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
